### ISSUE TITLE
Genepio not showing in ontologies list

### ISSUE THREAD

**Issue by ddooley** [EBISPOT/ols4#304]
We are wondering if there is a validation problem preventing OBO's GenEpiO from showing in OLS4? It is present in OLS current site right now.

**Comment by jamesamcl** [comment]
Seems like it:

```
load ontology from: http://purl.obolibrary.org/obo/genepio.owl
Using predownloaded file for http://purl.obolibrary.org/obo/genepio.owl
Downloading (not predownloaded) http://purl.obolibrary.org/obo/genepio.owl
org.apache.jena.riot.RiotException: Bad character in IRI (space): <http://purl.obolibrary.org/obo/The[space]...>
	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.error(ErrorHandlerFactory.java:146)
	at org.apache.jena.riot.lang.ReaderRIOTRDFXML$HandlerSink.convert(ReaderRIOTRDFXML.java:256)
	at org.apache.jena.riot.lang.ReaderRIOTRDFXML$HandlerSink.convert(ReaderRIOTRDFXML.java:273)
	at org.apache.jena.riot.lang.ReaderRIOTRDFXML$HandlerSink.statement(ReaderRIOTRDFXML.java:225)
	at org.apache.jena.rdfxml.xmlinput.impl.XMLHandler.triple(XMLHandler.java:72)
	at org.apache.jena.rdfxml.xmlinput.impl.ParserSupport.triple(ParserSupport.java:233)
	at org.apache.jena.rdfxml.xmlinput.states.WantDescription.aPredAndObj(WantDescription.java:109)
	at org.apache.jena.rdfxml.xmlinput.states.WantPropertyElement.theObject(WantPropertyElement.java:200)
	at org.apache.jena.rdfxml.xmlinput.states.WantPropertyElement.startElement(WantPropertyElement.java:129)
	at org.apache.jena.rdfxml.xmlinput.impl.XMLHandler.startElement(XMLHandler.java:111)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:518)
	at 
```

spaces aren't valid in IRIs; it should be encoded as %20

OLS4 is a bit more strict in some cases because it uses Jena to load the ontology files as RDF rather than OWLAPI.

**Comment by ddooley** [comment]
Closing this as it is resolved now.

**Comment by ddooley** [comment]
Can you try reloading genepio now? I fixed a few URI's and xml datetime field data types.

**Comment by ddooley** [comment]
Can you try again?  I've tested now against Jena riot command for stringent rdf syntax testing and genepio passes.

**Comment by ddooley** [comment]
@udp Please try loading GenEpiO again!  We have validated a 2nd time and found no issues.

**Comment by henrietteharmse** [comment]
@ddooley Still broken!

The issue is that there is arbitrary text where an IRI is expected in [http://purl.obolibrary.org/obo/genepio/imports/specification_enum_import.owl](http://purl.obolibrary.org/obo/genepio/imports/specification_enum_import.owl):

```
    <owl:Class rdf:about="http://purl.obolibrary.org/obo/GENEPIO_0100300">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/GENEPIO_0001522"/>
        <obo:IAO_0000114 rdf:resource="requires discussion"/>
        <obo:IAO_0000115 xml:lang="en">A data enumeration which references a set of named signs and symptoms entities.</obo:IAO_0000115>
        <obo:IAO_0000118 xml:lang="en">signs and symptoms</obo:IAO_0000118>
        <terms:contributor rdf:datatype="http://www.w3.org/2001/XMLSchema#string">https://orcid.org/0000-0002-8844-9165</terms:contributor>
        <terms:contributor rdf:datatype="http://www.w3.org/2001/XMLSchema#string">https://orcid.org/0000-0002-9578-0788</terms:contributor>
        <terms:date rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2022-01-19T18:23:15.862Z</terms:date>
        <rdfs:label xml:lang="en">health signs and symptoms enumeration</rdfs:label>
    </owl:Class>
```
The problematic bit is: ` <obo:IAO_0000114 rdf:resource="requires discussion"/>`

**Comment by ddooley** [comment]
I've done a pass to correct any rdf:resource="[not a uri]"  and so would like to see if reloading this will work now!

**Comment by ddooley** [comment]
Latest load seems to work, happy to say!
