### ISSUE TITLE
Using synonyms as search strings does not yield expected search results

### ISSUE THREAD

**Issue by ghost** [EBISPOT/ols4#309]
**Expected**: Searching for terms using synonyms returns results of ontology terms annotated with the synonyms.  For example, if ‘term x’ has synonym “A”, searching for “A” would return ‘term X’.

**Observed**: In OLS4, search results do not appear to take synonyms into account. For example, if ‘term x’ has synonym “A”, searching for “A” does not return ‘term X’ like it does in OLS3.
Two examples below.

**Example 1:**
OLS3
Ontology: CL
search string: "epsilon-acidophil" (an **exact** synonym of [mammotroph](http://purl.obolibrary.org/obo/CL_0002311)).
search results: [mammotroph](http://purl.obolibrary.org/obo/CL_0002311) appears in the first page of results

OLS4
_Can't constrain results to just CL from initial search_ (see https://github.com/EBISPOT/ols4/issues/308)
search string: "epsilon-acidophil"
search results: "No results!"

**Example 2:**
OLS3
Ontology: CL
search string: “Tnfrsf11a” (a **related** synonym of ‘[tumor necrosis factor receptor superfamily member 11A (mouse)](http://purl.obolibrary.org/obo/PR_O35305)’, a PR term in CL
search results: ‘[tumor necrosis factor receptor superfamily member 11A (mouse)](http://purl.obolibrary.org/obo/PR_O35305)’ appears in the first page of results

OLS4
search string: “Tnfrsf11a”
_Can't constrain results to just CL from initial search_ (see https://github.com/EBISPOT/ols4/issues/308)
search results: relevant search results appear, but none for terms that appear in CL.

If this is a user error, kindly advise if certain search parameters need to be adjusted in OLS4 to achieve the desired results.

**Proposed fix**: OLS4 takes synonyms (of all scopes) into account when returning search results.

**Comment by dosumis** [comment]
@henrietteharmse @udp - I think this is v.high priority.  Finding via synonym is one of the major use cases for OLS. More generally:

*  I'd really like to replicate OLS 4 autosuggest as far as possible.  A lot of work went in to tuning it.
*  How does this issue relate to ontology-specific config of synonyms, labels, etc?

**Comment by jamesamcl** [comment]
They are indexed using the properties from the config just as ols3. Must be an issue with the solr parameters used to query.

**Comment by jamesamcl** [comment]
Example 1. This is fixed now

Example 2. This is because of the "canonical definitions only" checkbox. We will need to change the default to be unchecked as it is confusing a lot of users.

**Comment by dosumis** [comment]
What's the point of the "canonical definitions only" checkbox?  Did anyone request this?

**Comment by jamesamcl** [comment]
It’s in OLS3 (isDefiningOntology) but wasn’t included in the UI. When I added it to the OLS4 UI I set it as on by default but clearly this is not desired behaviour.

The point is to find authoritative definitions of terms from the ontologies that defined them rather than possibly outdated/incomplete definitions from random ontologies that imported them.

**Comment by henrietteharmse** [comment]
There are 2 issues here:
1. In investigating this James discovered that the Solr index got corrupted. This is why "epsilon-acidophil" could not be found.
2.  "Tnfrsf11a" can not be found because "Canonical definitions only" is selected. Deselecting "Canonical definitions only" will allow "Tnfrsf11a" to be found.

**Comment by ghost** [comment]
Thanks, all, for the investigation.

Regarding point 2., I still do not find '[tumor necrosis factor receptor superfamily member 11A (mouse)](https://www.ebi.ac.uk/ols4/ontologies/flopo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPR_O35305)' in the search results when searching for the related synonym "Tnfrsf11a" with "Canonical definitions only" deselected.

Rather, [the parent class](http://purl.obolibrary.org/obo/PR_000001954) appears in the results. When I select it in the search results, it takes me to a page where "Canonical definitions only" is toggled back on and the tree is empty. I suspect the parent class returns because "TNFRSF11A" (all caps) is an exact synonym for that term.

![searching_related_syn](https://user-images.githubusercontent.com/95643797/234542818-31e849e5-6ce4-47bc-bc63-b93fe15995fc.gif)

**Comment by ghost** [comment]
It seems other **related** synonyms are not returning the associated classes.

Another example, '[diffuse bipolar 1 cell](http://purl.obolibrary.org/obo/CL_4033027)' does not return when searching by the related synonym "DB1 bipolar", even after deselecting "Canonical definitions only" .
