### ISSUE TITLE
Chemical Analysis Ontology short_form codes are incorrectly formatted

### ISSUE THREAD

**Issue by stuchalk** [EBISPOT/ols4#699]
**Describe the bug**
The CAO ontology terms in OLS have incorrectly formatted short_form codes throughout.

**To Reproduce**
1. Go to https://www.ebi.ac.uk/ols4/api/ontologies/cao/terms?lang=en
2. Scroll down to any term
3. Look at the contents of the short_form field

**Expected behavior**
Go to the ontology at https://champ.stuchalk.domains.unf.edu/images/ontology/cao.owl and verify the term id format, 'CAO_\d{6}' in regex.

**Comment by haideriqbal** [comment]
Thanks for reporting @stuchalk! This doesn't look right and we'll look into it.

**Comment by stuchalk** [comment]
Thanks!

**Comment by haideriqbal** [comment]
This has been fixed in production now!

**Comment by stuchalk** [comment]
Thank you!

**Comment by jamesamcl** [comment]
They still look wrong to me?

      "short_form" : "CAO_CAO_000001",
      "obo_id" : "CAO_CAO:000001",

**Comment by jamesamcl** [comment]
Possibly related: https://github.com/EBISPOT/ols4/issues/721 ?

**Comment by stuchalk** [comment]
You are correct they are still wrong, and quite likely related to #721...

**Comment by haideriqbal** [comment]
Probably its a deployment issue let me check! it shows correct format on wwwdev

https://wwwdev.ebi.ac.uk/ols4/api/ontologies/cao/terms?lang=en

**Comment by haideriqbal** [comment]
The production system didn't have the latest config which resulted in this... in the next release cycle which will be tomorrow probably this will be fixed. I will keep an eye on it.

**Comment by haideriqbal** [comment]
I can see this fixed in production now! closing this.
